### ISSUE TITLE
desktop-launch: line 199: [: too many arguments

### ISSUE THREAD

**Issue by ddennedy** [ubuntu/snapcraft-desktop-helpers#114]
Today, I was updating my snap and testing it before publishing it. I got the error when trying to run it:
```
ddennedy@MS-7593:~/src/mlt_web$ shotcut
cp: '/home/ddennedy/.config/user-dirs.locale' and '/home/ddennedy/.config/user-dirs.locale' are the same file
/snap/shotcut/x4/bin/desktop-launch: line 199: [: too many arguments
```
Upon reverting to the previous version of the app (snap revert), it works. I see bin/desktop-launch did change between versions. Next, I moved /home/ddennedy/.config/user-dirs.locale out of the way and tried again. This time I got:
```
ddennedy@MS-7593:~/src/mlt_web$ shotcut
/snap/shotcut/x4/bin/desktop-launch: line 23: /home/ddennedy/.config/user-dirs.locale: No such file or directory
/snap/shotcut/x4/bin/desktop-launch: line 190: [: /home/ddennedy/../../media/File: binary operator expected
```
I have some interesting mounts on this machine. I have these NFS mounts:
- fileserver:/srv/storage on /media/File Server type nfs 
- fileserver:/srv/home/ddennedy on /home/ddennedy/net/ddennedy type nfs
And then I have symbol links in my home for some special directories:
```
lrwxrwxrwx   1 ddennedy ddennedy        37 Oct 16  2017 Documents -> /home/ddennedy/net/ddennedy/Documents
lrwxrwxrwx   1 ddennedy ddennedy        37 Oct 16  2017 Downloads -> /home/ddennedy/net/ddennedy/Downloads
lrwxrwxrwx   1 ddennedy ddennedy        24 Jun 11  2016 Music -> /media/File Server/music
lrwxrwxrwx   1 ddennedy ddennedy        25 Jun 11  2016 Pictures -> /media/File Server/photos
```
Yes, I know it is a strange, abnormal setup. :-/
Next, I unmounted those NFS shares, and I get the following, which is fine with me:
```
/home/ddennedy/Downloads was removed, reassigning DOWNLOAD to homedir
/home/ddennedy/Documents was removed, reassigning DOCUMENTS to homedir
/home/ddennedy/Music was removed, reassigning MUSIC to homedir
/home/ddennedy/Pictures was removed, reassigning PICTURES to homedir
```
Just thought I'd share this in case you want to try to work around weird setups.

**Comment by Lin-Buo-Ren** [comment]
These all seem to be unsanitized word splitting errors, which should be mostly fixed by PR #123 and #129

**Comment by ddennedy** [comment]
As an update, upon updating my snap July 1 and then again August 1, I still see messages `desktop-launch: line 207: [: too many arguments` at snap launch. However, the snap runs without having to remove my weird nfs mounts unlike before.

**Comment by Lin-Buo-Ren** [comment]
Probably here:

```bash
  # If we aren't creating new links, check if we have content saved in old locations and move it
  for d in DOCUMENTS DESKTOP DOWNLOAD MUSIC PICTURES VIDEOS PUBLICSHARE TEMPLATES; do
    old=`eval "$(echo "echo \\$OLD_XDG_${d}_DIR")"`
    new=`eval "$(echo "echo \\$XDG_${d}_DIR")"`
    if [ -L "$old" ] && [ -d "$new" ] && [ `readlink "$old"` != "$new" ]; then
      mv "$old"/* "$new"/ 2>/dev/null
    elif [ -d "$old" ] && [ -d "$new" ] && [ "$old" != "$new" ]; then
      mv "$old"/* "$new"/ 2>/dev/null
    fi
  done
```

However [the eval operation is risky](http://mywiki.wooledge.org/BashFAQ/048) so I still don't know how to deal with this as of now.
